---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/exporters/prowlarr-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
