---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app ghostfolio-proxy
  labels:
    kubernetes.io/service-name: *app
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Portfolio management
    gethomepage.dev/group: Vermögen
    gethomepage.dev/icon: ghostfolio
    gethomepage.dev/name: Ghostfolio
    gethomepage.dev/weight: "1"
    #gethomepage.dev/widget.type=ghostfolio
    #gethomepage.dev/widget.url=http://ghostfolio-proxy.finance
    #gethomepage.dev/widget.key=${GFOLIO_BEARER_TOKEN}
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "gfolio.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ghostfolio-proxy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app ghostfolio-proxy # Must be equal to Service name for automatic mapping
  namespace: home
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 3333
endpoints:
  - addresses:
      - 192.168.2.121
