---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mosquitto
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 120m
  path: "./kubernetes/apps/home/mosquitto/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    #- name: volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: mosquitto-data
      VOLSYNC_CAPACITY: 512Mi
