---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: vm-additional-scrape-configs
  namespace: observability
stringData:
  prometheus-additional.yaml: |

    - job_name: node-exporter
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - raspi2.internal:9100
            - raspi3.internal:9100

    - job_name: smartctl-exporter
      scrape_interval: 10m
      scrape_timeout: 10s
      honor_timestamps: true
      static_configs:
        - targets:
            - ha.internal:9633
