---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: step-ca
spec:
  interval: 1h
  chart:
    spec:
      chart: step-certificates
      version: 1.27.4
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
