---
# Area
- { name: "area/ansible",            color: "0e8a16" }
- { name: "area/docs",               color: "0e8a16" }
- { name: "area/bootstrap",          color: "0e8a16" }
- { name: "area/flux",               color: "0e8a16" }
- { name: "area/github",             color: "0e8a16" }
- { name: "area/hardware",           color: "0052cc" }
- { name: "area/k8s",                color: "0e8a16" }
- { name: "area/taskfile",           color: "0e8a16" }
# Namespace
- { name: "ns/kube-system",          color: "d4c5f9" }
- { name: "ns/kube-tools",           color: "d4c5f9" }
- { name: "ns/flux-system",          color: "d4c5f9" }
- { name: "ns/database",             color: "d4c5f9" }
- { name: "ns/storage",              color: "d4c5f9" }
- { name: "ns/finance",              color: "d4c5f9" }
- { name: "ns/home",                 color: "d4c5f9" }
- { name: "ns/network",              color: "d4c5f9" }
- { name: "ns/o11y",                 color: "d4c5f9" }
- { name: "ns/office",               color: "d4c5f9" }
- { name: "ns/security",             color: "d4c5f9" }
- { name: "ns/media",                color: "d4c5f9" }
- { name: "ns/download",             color: "d4c5f9" }
- { name: "ns/health",               color: "d4c5f9" }
# Distro
- { name: "distro/talos",            color: "ffc300" }
# Renovate
- { name: "renovate/container",      color: "027fa0" }
- { name: "renovate/github-action",  color: "027fa0" }
- { name: "renovate/pre-commit",     color: "027fa0" }
- { name: "renovate/github-release", color: "027fa0" }
- { name: "renovate/helm",           color: "027fa0" }
- { name: "renovate/grafana-dashboard", color: "027fa0" }
# Semantic Type
- { name: "type/digest",             color: "ffec19" }
- { name: "type/patch",              color: "ffec19" }
- { name: "type/minor",              color: "ff9800" }
- { name: "type/major",              color: "f6412d" }
- { name: "type/break",              color: "f6412d" }
# Priority for issues
- { name: "prio: critical",          color: "ff00ff" }
- { name: "prio: high",              color: "ee0701" }
- { name: "prio: medium",            color: "ffec19" }
# Uncategorized
- { name: "hold/upstream",           color: "ee0701" }
- { name: "broken-links",            color: "ee0701" }
