---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/bootstrap/**/*"
distro/talos:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/bootstrap/talos/**/*"
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/apps/**/*"
area/flux:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/flux/**/*"
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - ".taskfiles/**/*"
          - "Taskfile*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "README.md"
