apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-sops-secrets
  namespace: flux-system
spec:
  interval: 60m
  url: "ssh://git@github.com/volschin/home-sops-secrets.git"
  secretRef:
    name: github-deploy-key
