apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: &app home-sops-secrets
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/volschin/home-sops-secrets
  secretRef:
    name: *app
