---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app trivy-operator
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 360m
  retryInterval: 5m
  prune: true
  wait: true

  dependsOn:
    - name: kube-prometheus-stack-crds

  path: ./kubernetes/apps/security/trivy/operator
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
