---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        HASS_DARKSKY_API_KEY: "{{ .HASS_DARKSKY_API_KEY }}"
        HASS_ELEVATION: "{{ .HASS_ELEVATION }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        HASS_PIRATE_WEATHER_API_KEY: "{{ .HASS_PIRATE_WEATHER_API_KEY }}"
        HASS_POSTGRES_URL: |-
          postgresql://{{ .HASS_POSTGRES_USER }}:{{ .HASS_POSTGRES_PASS }}@postgres-rw.database.svc.cluster.local/home_assistant
        INIT_POSTGRES_DBNAME: home_assistant
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .HASS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .HASS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: home-assistant
