---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./proxy.yaml
  #- ./externalsecret.yaml
  #- ./helmrelease.yaml
  # Templates
  #- ../../../../templates/gatus/guarded
