---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app tubearchivist
  labels:
    kubernetes.io/service-name: *app
  annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "ta.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tubearchivist
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8777
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app tubearchivist # Must be equal to Service name for automatic mapping
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8777
endpoints:
  - addresses:
      - ha.fritz.box
