---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app tubearchivist
  labels:
    kubernetes.io/service-name: *app
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Player
    gethomepage.dev/name: TubeArchivist
    gethomepage.dev/icon: tube-archivist
    gethomepage.dev/description: YouTube management
    gethomepage.dev/weight: "2"
  #  gethomepage.dev/widget.type: tubearchivist
  #  gethomepage.dev/widget.url: http://tubearchivist.media:80
  #  gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_TA_TOKEN}}` }}"
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "ta.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tubearchivist
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8777
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app tubearchivist # Must be equal to Service name for automatic mapping
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8777
endpoints:
  - addresses:
      - 192.168.2.121
