---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ohif-viewer
  namespace: flux-system
spec:
  targetNamespace: health
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/health/ohif-viewer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
#  dependsOn:
#    - name: external-secrets-stores
  wait: false
  interval: 2h
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
