---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
data:
  # URLS
  IMMICH_SERVER_URL: http://immich-server.office.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.office.svc.cluster.local:3003
  PUBLIC_IMMICH_SERVER_URL: https://photos.${SECRET_DOMAIN}
  # SETTINGS
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: log
  NODE_ENV: production
  UPLOAD_LOCATION: /usr/src/app/upload
  # REDIS
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_DBINDEX: "1"
  REDIS_PORT: "6379"
