---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zwave-network-key
  namespace: home
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ZWAVE_NETWORK_KEY
  data:
  - secretKey: data
    remoteRef:
      key: Test_secret
