---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: zwave-key
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ZWAVE_KEY
  data:
  - secretKey: data
    remoteRef:
      key: Test_secret
