---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./angelnu.yaml
  - ./aqua.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./influxdata.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kepler.yaml
  - ./kyverno.yaml
  - ./kyverno-reporter.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./portainer.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./smallstep.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./victoria-metrics.yaml
  - ./volschin.yaml
  - ./weave-gitops.yaml
