---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: influxdb
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/influxdb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 360m
