---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-runners
  namespace: flux-system
spec:
  targetNamespace: dev
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 6h
  path: "./kubernetes/apps/dev/forgejo-runners/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
