---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
          - name: "tplink-bluetooth"
            matchOn:
            - usbId:
              class: ["224"]
              vendor: ["2357"]
              device: ["0604"]
