---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-device
spec:
  rules:
    - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["ff"]
                    vendor: ["1a86"]
                    device: ["7523"]
