apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:shBdYNmLu8JXohxfvA/oTF+LUflPT/+RD3tWf5cX7yN+ODqH,iv:AR5JJktvx5q0ops41gr0DC377Tbpqt3qnp/L+1OITJk=,tag:iTunVjD2VISAz5hGjF2W6g==,type:str]
    credentials.json: ENC[AES256_GCM,data:IVSIBIWNG03/30y5CVB153nX1sMXPwLV+/k6D85L2sjlK9ebMwGc2QU+QWp+VLQvM6dVsab7xujOVZmFDNhU5VOIFYBUvQi464+XxocfN5O5em8p1TlMsnrl/ksPECGUg1cJbWyvEL9U3Eh5fg2avrAW9pFBOzupG+U+M1q8LCTW8WOBMCb22XWKx39auX1RDW/2c3c4KiOWdvloeNd2/wc9cvXqFea5I19T6kyiVw==,iv:O1+TRg6tfmY3vS8snevsR6JqwRi3SPQ17JsaCHOaM9s=,tag:3GmnCopPlwhXmAEPJ/TruQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1an5k47lwzqkn0rq0f796ayfwa6sd9qrp4y8vctc5fha3c3tpdv8sk6dr6s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOEVzYnNzMlBWZThMWEI1
            QTVkVFVpaVdNcDN3YzVUUFFUTFJpeHBTaEZjCi9wQUIzc1A4NjFMalIraWcyZDVD
            ak9Sd0hVSXpXTjJXWGt4ZUJjKzd6clEKLS0tIDJocVZNbmZCVEkyZ3FSeWZjRWND
            aW44YkNVZ0tNYlRzeGxHbHBya29VVkEKJXLlVxsRRkAfRegjAI1zgWiYOgwmSjoW
            GMINzUAQShO7jOn0ndGlIl1h9ZXEYiaHwAqRxhyDbp+qQ1mJoCqbJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-25T10:40:02Z"
    mac: ENC[AES256_GCM,data:LMJrZtCVlHGxAmWvWKVl6yAOpmbN8bT/QdiBzEZC6uontmNT5wxTWMOFVydRiXhgMoikocPEYJQoLEtWk2AoggqdvylJ5rB5kFaaeKnpSZnRm7XNArHq4YGzNXqJY50u2iSnaNTMvo2SIZ6HINd1xSNYOD5SNzRotBD6o+9ZIkE=,iv:WHkXdsZJhtKdOZntrGS95Z6P1IUBEv7z8CKA9j22zl0=,tag:bfEAhLC8T6jh+c0sk4JwQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
