---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
  namespace: office
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: linkwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_NEXTAUTH_SECRET }}"
        DATABASE_URL: "postgresql://{{ .LINKWARDEN_POSTGRES_USER }}:{{ .LINKWARDEN_POSTGRES_PASS }}@{{ .POSTGRES_HOST }}/{{ .LINKWARDEN_POSTGRES_DBNAME }}"
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .LINKWARDEN_POSTGRES_DBNAME }}"
        INIT_POSTGRES_USER: "{{ .LINKWARDEN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LINKWARDEN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: linkwarden
    - extract:
        key: cnpg
