apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image-signing
spec:
  validationFailureAction: Audit
  webhookTimeoutSeconds: 30
  rules:
    - name: check-image-signed
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "*"
