---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: app-template
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/bjw-s/helm/app-template
  ref:
    tag: "3.3.1"
#  verify:
#    provider: cosign
#    matchOIDCIdentity:
#      - issuer: "^https://token.actions.githubusercontent.com$"
#        subject: "^https://github.com/bjw-s/helm-charts.*$"
