---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/volschin/charts/weave-gitops
  ref:
    tag: "4.0.37"
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/volschin/weave-gitops.*$"
