---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-address
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        address: "{{ .ALERTMANAGER_URL }}"
  dataFrom:
    - extract:
        key: alertmanager
#stringData:
#    address: https://username:password@<alertmanager-url>/api/v2/alerts/"
