---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app alexa-fhem-webhook
  namespace: home
  labels:
    kubernetes.io/service-name: *app
  annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
spec:
  ingressClassName: external
  rules:
  - host: "alexa.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alexa-fhem-webhook
  namespace: home
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app alexa-fhem-webhook # Must be equal to Service name for automatic mapping
  namespace: home
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 3000
endpoints:
  - addresses:
      - 192.168.2.121
