---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bws-secret
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-css-certs
        key: ca.crt
      organizationID: ${bws_organizationID}
      projectID: ${bws_projectID_talos}
   #   caBundle: ${bws_caBundle}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager-common
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bws-secret
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-css-certs
        key: ca.crt
      organizationID: ${bws_organizationID}
      projectID: ${bws_projectID_common}
   #   caBundle: ${bws_caBundle}
