---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: authelia-secret
    template:
      data:
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
     #   REDIS_PASSWORD:
     #   REDIS_SENTINEL_PASSWORD:
        GRAFANA_OAUTH_CLIENT_SECRET_DIGEST: "{{ .GRAFANA_OAUTH_CLIENT_SECRET_DIGEST }}"
        MINIFLUX_OAUTH_CLIENT_SECRET_DIGEST: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET_DIGEST }}"
        OCIS_OAUTH_CLIENT_SECRET: "{{ .OCIS_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: authelia
