---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
#  - ../../../../templates/gatus/external
configMapGenerator:
  - name: authelia-configmap
    namespace: security
    files:
      - ./config/configuration.yml
      - ./config/users_database.yml
generatorOptions:
  disableNameSuffixHash: true
  # annotations:
  #   kustomize.toolkit.fluxcd.io/substitute: disabled
