---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebridge
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/homebridge/homebridge
              tag: 2024-06-27@sha256:be09c4402c351520069014ba77a6d12f22021294c04125b827a8e7cb5b79b9da
            env:
              TZ: "${TIMEZONE}"
              ENABLE_AVAHI: "1"
              HOMEBRIDGE_CONFIG_UI: "1"
              HOMEBRIDGE_CONFIG_UI_PORT: "8080"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8581
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 750Mi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      #    homepage.group=Apple HomeKit
      #    homepage.name=Homebridge FHEM
      # homepage.icon=homebridge.svg
      # homepage.description=FHEM für iPhone
      # homepage.widget.type=homebridge
      # homepage.widget.url=http://ha.local:8080/
      # homepage.widget.fields=["updates", "child_bridges"]
      # homepage.widget.username=externalsecret
      # homepage.widget.password=externalsecret
        hosts:
          - host: &host "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          hosts:
            - *host
    configMaps:
      config:
        enabled: true
        nameOverride: startup-sh
        data:
          startup.sh: |-
            #!/bin/sh
            npm install --save homebridge-dummy@latest
            npm install --save homebridge-myq@latest
            npm install --save homebridge-nest@latest
            npm install --save homebridge-orbit-irrigation@latest
            npm install --save homebridge-tplink-smarthome@latest
            npm install --save -g homebridge-camera-ui@latest
    persistence:
      homebridge:
        enabled: true
        existingClaim: homebridge-config
      startup-sh:
        enabled: true
        type: configMap
        name: homebridge-startup-sh
        globalMounts:
          - path: /homebridge/startup.sh
            subPath: startup.sh
            defaultMode: 493
