---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homebridge-config
  namespace: home
  labels:
    snapshot.home.arpa/enabled: "true"
    app.kubernetes.io/instance: homebridge
    app.kubernetes.io/name: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: openebs-zfspv-ssd
