---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-helm-values
  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: internal
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/description: Network, Service & Security Observability
            gethomepage.dev/group: Monitoring
            gethomepage.dev/icon: cilium.png
            gethomepage.dev/name: Cilium Hubble
            # gethomepage.dev/widget.type: "emby"
            # gethomepage.dev/widget.url: "https://hubble.${SECRET_DOMAIN}"
            # gethomepage.dev/pod-selector: ""
            gethomepage.dev/weight: 10 # optional
            gethomepage.dev/instance: "intern" # optional
          hosts: ["hubble.${SECRET_DOMAIN}"]
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
