---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: recyclarr-secret
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
        property: RADARR__API_KEY
    - extract:
        key: sonarr
        property: SONARR__API_KEY
