---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./airsensor/ks.yaml
  - ./fhem/ks.yaml
  - ./hmcfgusb/ks.yaml
  - ./mosquitto/ks.yaml
  - ./presence/ks.yaml
  - ./home-assistant/ks.yaml
  - ./zwave/ks.yaml
