---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./it-tools/ks.yaml
  - ./mosquitto/ks.yaml
  - ./portainer/ks.yaml
  - ./zwave/ks.yaml
