---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./alexa-fhem/ks.yaml
  - ./echo-server/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./zwave/ks.yaml
