---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        # Sonarr
        SONARR__API_KEY: "{{ .SONARR__API_KEY }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_USER: "{{ .SONARR_POSTGRES_USER }}"
        SONARR__POSTGRES_PASSWORD: "{{ .SONARR_POSTGRES_PASS }}"
        SONARR__POSTGRES_HOST: &dbhost ${POSTGRES_URL}
        # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: "{{ .SONARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .SONARR_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: sonarr
    - extract:
        key: cloudnative-pg
