---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app stirling-pdf
  namespace: flux-system
spec:
  targetNamespace: office
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-dns
  path: ./kubernetes/apps/office/stirling-pdf/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 60m
  retryInterval: 1m
  timeout: 5m
