---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 120m
  path: ./kubernetes/apps/observability/exporters/node-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
