---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whisparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: whisparr-secret
    template:
      engineVersion: v2
      data:
        # App
        WHISPARR__API_KEY: "{{ .WHISPARR__API_KEY }}"
        WHISPARR__POSTGRES_HOST: &dbHost ${POSTGRES_URL}
        WHISPARR__POSTGRES_PORT: "5432"
        WHISPARR__POSTGRES_USER: &dbUser "{{ .WHISPARR_POSTGRES_USER }}"
        WHISPARR__POSTGRES_PASSWORD: &dbPass "{{ .WHISPARR_POSTGRES_PASS }}"
        WHISPARR__POSTGRES_MAIN_DB: whisparr_main
        # Postgres Init
        INIT_POSTGRES_DBNAME: whisparr_main
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: whisparr
    - extract:
        key: cloudnative-pg
