---
apiVersion: v1
kind: Service
metadata:
  name: arr
  namespace: media
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: arr # Must be equal to Service name for automatic mapping
  namespace: media
subsets:
- addresses:
  - ip: 192.168.2.132 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 89
