---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: readarr-secret
    template:
      engineVersion: v2
      data:
        # App
        READARR__API_KEY: "{{ .READARR__API_KEY }}"
        READARR__POSTGRES_HOST: &dbHost ${POSTGRES_URL}
        READARR__POSTGRES_PORT: "5432"
        READARR__POSTGRES_USER: &dbUser "{{ .READARR_POSTGRES_USER }}"
        READARR__POSTGRES_PASSWORD: &dbPass "{{ .READARR_POSTGRES_PASS }}"
        READARR__POSTGRES_MAIN_DB: readarr_main
        READARR__POSTGRES_LOG_DB: readarr_log
        READARR__POSTGRES_CACHE_DB: readarr_cache
        # Postgres Init
        INIT_POSTGRES_DBNAME: readarr_main readarr_log readarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: readarr
    - extract:
        key: cloudnative-pg
