---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  file:
    path: '/config/users_database.yml'

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: ${SECRET_DOMAIN}_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

notifier:
  disable_startup_check: true
  smtp:
    address: smtp://smtp.${SECRET_DOMAIN}:25
    sender: Authelia <authelia@${SECRET_DOMAIN}>
    disable_require_tls: false

totp:
  disable: false
  issuer: auth.${SECRET_DOMAIN}

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "${SECRET_HOMELAN_IPV4}"]
  rules:
    # This just reduces logging noise in authelia
    - domain:
        - whoami.${SECRET_DOMAIN}
      resources:
        - ^/health$
        - ^/health/
      policy: bypass

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_id: grafana
        client_name: Grafana
        client_secret: "$${GRAFANA_OAUTH_CLIENT_SECRET_DIGEST}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        token_endpoint_auth_method: client_secret_post
        userinfo_signed_response_alg: none
      - client_id: miniflux
        client_name: Miniflux
        client_secret: "$${MINIFLUX_OAUTH_CLIENT_SECRET_DIGEST}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://miniflux.${SECRET_DOMAIN}/oauth2/oidc/callback"]
        userinfo_signed_response_alg: none
