---
apiVersion: v1
kind: Secret
metadata:
  name: ghostfolio-secret
  namespace: finance
type: Opaque
stringData:
  # App
  ACCESS_TOKEN_SALT: "${GHOSTFOLIO_ACCESS_TOKEN_SALT}"
  DATABASE_URL: postgresql://${GHOSTFOLIO_POSTGRES_USER}:${GHOSTFOLIO_POSTGRES_PASSWORD}@postgres-rw.data.svc.cluster.local:5432/ghostfolio
  JWT_SECRET_KEY: "${GHOSTFOLIO_JWT_SECRET_KEY}"
  # Postgres Init
  INIT_POSTGRES_DBNAME: ghostfolio
  INIT_POSTGRES_HOST: postgres-rw.data.svc.cluster.local
  INIT_POSTGRES_USER: "${GHOSTFOLIO_POSTGRES_USER}"
  INIT_POSTGRES_PASS: "${GHOSTFOLIO_POSTGRES_PASSWORD}"
  INIT_POSTGRES_SUPER_PASS: "${POSTGRES_SUPER_PASS}"
