---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name ghostfolio-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        ACCESS_TOKEN_SALT: "${GHOSTFOLIO_ACCESS_TOKEN_SALT}"
        DATABASE_URL: postgresql://${GHOSTFOLIO_POSTGRES_USER}:${GHOSTFOLIO_POSTGRES_PASSWORD}@postgres-rw.data.svc.cluster.local:5432/ghostfolio
        JWT_SECRET_KEY: "${GHOSTFOLIO_JWT_SECRET_KEY}"
  dataFrom:
  - extract:
      key: ghostfolio
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name ghostfolio-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: ghostfolio-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        PROWLARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        PROWLARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
        PROWLARR__POSTGRES__USER: '{{ .user }}'
        PROWLARR__POSTGRES__PASSWORD: '{{ .password }}'
        PROWLARR__POSTGRES__MAINDB: '{{ .dbname }}'
  dataFrom:
  - extract:
      key: postgres-pguser-ghostfolio
