---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ghostfolio
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      ghostfolio:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/volschin/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: ghostfolio-secret
        containers:
          app:
            image:
              repository: docker.io/ghostfolio/ghostfolio
              tag: 2.114.0@sha256:71aca54a6961069e20bcd17c6d55ebbd7f33220af37ff21d2e919ac66a4fd39e
            env:
              NODE_ENV: production
              REDIS_HOST: dragonfly.database.svc.cluster.local.
              REDIS_PORT: 6379
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3333
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Finanzen
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/icon: ghostfolio.png
          gethomepage.dev/id: "{{ .Release.Name }}"
          gethomepage.dev/description: Portfolio Management
        hosts:
          - host: &host "gfolio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
