---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name prowlarr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY }}"
  dataFrom:
  - extract:
      key: prowlarr
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name prowlarr-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: prowlarr-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        PROWLARR__POSTGRES__HOST: '{{ index . "pgbouncer-host" }}'
        PROWLARR__POSTGRES__PORT: '{{ index . "pgbouncer-port" }}'
        PROWLARR__POSTGRES__USER: '{{ .user }}'
        PROWLARR__POSTGRES__PASSWORD: '{{ .password }}'
        PROWLARR__POSTGRES__MAINDB: '{{ .dbname }}'
  dataFrom:
  - extract:
      key: postgres-pguser-prowlarr
