---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app victoria-metrics
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./kubernetes/apps/observability/victoria-metrics/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
