---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      mosquitto:
        type: statefulset
        replicas: 2
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            args:
            - sh
            - -c
            - exec mosquitto -c "/config/$(hostname).conf"
            image:
              repository: ghcr.io/vaskozl/mosquitto
              tag: 2.0.18@sha256:729993997bace33e2399ae69ada6a93f537d2b8ba94a87e0110977f874e962c7
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 2m
                memory: 8Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        runAsGroup: 568
        runAsNonRoot: true
        runAsUser: 568
        seccompProfile:
          type: RuntimeDefault
    persistence:
      config:
        name: mosquitto-config
        type: configMap
      data:
        existingClaim: mosquitto-data
        advancedMounts:
          mosquitto:
            app:
              - path: /data
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mqtt.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: 192.168.2.30
        ports:
          mqtt:
            enabled: true
            port: 1883
 #     mosquitto-secret:
 #       type: secret
 #       name: mosquitto-secret
 #       advancedMounts:
 #         mosquitto:
 #           init-config:
 #             - path: /tmp/secret
 #     mosquitto-externalconfig:
 #       type: emptyDir
 #       globalMounts:
 #         - path: /mosquitto/external_config
