---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
 # - ./externalsecret.yaml
 # - ../../../../templates/volsync
configMapGenerator:
- name: mosquitto-config
  files:
  - config/mosquitto-0.conf
  - config/mosquitto-1.conf
configurations:
- kustomizeconfig.yaml
#generatorOptions:
#  disableNameSuffixHash: true
