---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: policy-reporter
    namespace: flux-system
  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    api:
      enabled: true
    ui:
      enabled: true
      plugins:
        kyverno: true
      ingress:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Policy Reporting
          gethomepage.dev/group: Security
          gethomepage.dev/icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/kyverno/icon/color/kyverno-icon-color.svg
          gethomepage.dev/id: "{{ .Release.Name }}"
          gethomepage.dev/name: Kyverno Policy Reporter
        hosts:
          - host: "policy-report.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
           #     service:
           #       identifier: app
           #       port: http
    kyvernoPlugin:
      enabled: true
    global:
      plugins:
        kyverno: true
    ingress:
      enabled: false
      className: internal
      hosts:
        - host: "policy-reporter.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
