---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app influxdb-proxy
  namespace: database
  labels:
    kubernetes.io/service-name: *app
  annotations:
   # nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "ts.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-proxy
  namespace: home
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app influxdb-proxy # Must be equal to Service name for automatic mapping
  namespace: home
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8086
endpoints:
  - addresses:
      - 192.168.2.121
