---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR__API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost ${POSTGRES_URL}
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR_POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR_POSTGRES_PASS }}"
        RADARR__POSTGRES_MAIN_DB: &db radarr_main
        # Postgres Init
        INIT_POSTGRES_DBNAME: *db
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: cloudnative-pg
