---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: media
  labels:
    kubernetes.io/service-name: arr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Downloads
    gethomepage.dev/name: Prowlarr
    gethomepage.dev/icon: prowlarr.svg
    gethomepage.dev/description: Torrent Indexer Management
  #  gethomepage.dev/widget.type: prowlarr
  #  gethomepage.dev/widget.url: http://arr.media/prowlarr/
  #  gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_PROWLARR_TOKEN}}` }}"
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: "prowlarr.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /prowlarr/
        pathType: Prefix
        backend:
          service:
            name: arr
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arr
  namespace: media
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 89
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: arr # Must be equal to Service name for automatic mapping
  namespace: media
  labels:
    kubernetes.io/service-name: arr
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 89
endpoints:
  - addresses:
      - 192.168.2.121
