---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  chartRef:
    kind: OCIRepository
    name: aqua-trivy
    namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/aquasecurity/trivy-operator/blob/v0.12.0/deploy/helm/values.yaml
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      scanJobsConcurrentLimit: 2
      clusterSbomCacheEnabled: true
      metricsVulnIdEnabled: false
      exposedSecretScannerEnabled: false
    serviceMonitor:
      enabled: true
    trivy:
      repository: ghcr.io/aquasecurity/trivy
      tag: 0.54.1
      ignoreUnfixed: true
      severity: MEDIUM,HIGH,CRITICAL
  interval: 6h
