---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # https://github.com/aquasecurity/trivy-operator/blob/v0.12.0/deploy/helm/values.yaml
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      scanJobsConcurrentLimit: 2
      clusterSbomCacheEnabled: true
      metricsVulnIdEnabled: false
      exposedSecretScannerEnabled: false
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
      severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  interval: 60m
