---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  chartRef:
    kind: OCIRepository
    name: trivy-operator
    namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      scanJobsConcurrentLimit: 2
#      builtInTrivyServer: true
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          memory: 500M
  interval: 60m
