---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: trivy-operator
      version: '0.24.1'
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      scanJobsConcurrentLimit: 2
#      builtInTrivyServer: true
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 500m
          memory: 500M
  interval: 15m
