---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set
spec:
  interval: 120m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: gha-runner-controller
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: gha-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: gha-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: gha-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    nameOverride: gha-runner-scale-set
    runnerScaleSetName: gha-runner-scale-set
    githubConfigUrl: https://github.com/volschin/home-ops
    minRunners: 1
    maxRunners: 4
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/volschin/actions-runner:2.320.0@sha256:6e1173ae49f6341d802bac81366f5a0826a52d07512fce4f3310df0a29e7750c
            command: ["/home/runner/run.sh"]
    controllerServiceAccount:
      name: gha-runner-controller
      namespace: dev
