---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: portainer
  namespace: networking
spec:
  interval: 5m
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  chart:
    spec:
      chart: portainer
      version: 1.0.51
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      size: "256Mi"
      storageClass: longhorn
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/appName: "portainer"
        hajimari.io/icon: "pier-crane"
        hajimari.io/group: "monitoring"
      hosts:
        - host: &host "portainer.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
