---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kyverno-reporter
  namespace: flux-system
spec:
  interval: 6h
  prune: true
  targetNamespace: kyverno
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kyverno
  path: ./kubernetes/apps/kyverno/reporter/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
