---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app podinfo
  namespace: flux-system
spec:
  targetNamespace: kube-tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kube-tools/podinfo/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 6h
  timeout: 5m
