---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: office
data:
  bookmarks.yaml: |
    - Developer:
      - Github:
        - icon: github-light.png
          href: https://github.com/
      - Terraform:
        - icon: terraform.svg
          href: https://volschin.app.spacelift.io/
      - Homepage Documentation:
        - icon: homepage.png
          href: https://gethomepage.dev/
      - ArtifactHUB:
        - icon: https://avatars.githubusercontent.com/u/62354979?s=200&v=4
          href: https://artifacthub.io/
      - Flux documentation:
        - icon: flux-cd.svg
          href: https://fluxcd.io/flux/guides/
      - Docker Hub:
        - icon: docker-moby.svg
          href: https://hub.docker.com/
      - StepSecurity:
        - icon: stepsecurity
          href: https://app.stepsecurity.io/github/volschin/actions/dashboard
      - FireHOL IP Blacklists:
        - icon: /icons/firehol.png
          href: https://iplists.firehol.org/
      - PTB Uhr:
        - icon: /icons/ptbuhr.png
          href: https://uhr.ptb.de/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Infrastructure:
        - AdGuard Home:
            href: https://adguard
            icon: adguard-home.png
        - Fritz!Box:
            href: https://fritz.box
            icon: avmfritzbox.png
        - OPNsense:
            href: https://opnsense
            icon: opnsense.png
    - Observability:
        - Prometheus (storage):
            href: https://prometheus
            icon: prometheus.png
    - Storage:
        - Filebrowser:
            href: https://filebrowser
            icon: filebrowser.png
        - Kopia:
            href: https://kopia
            icon: kopia.png
        - Minio:
            href: https://minio
            icon: minio.png
    - Tools:
        - Zot Registry:
            href: https://registry
            icon: logo.svg
  settings.yaml: |
    background:
      image: https://images.unsplash.com/photo-1633259584604-afdc243122ea
      opacity: 10
    fiveColumns: true
    headerStyle: clean
    hideErrors: true
    hideVersion: true
    iconStyle: theme
    layout:
      Automation:
        style: column
      Infrastructure:
        style: column
      Observability:
        style: column
      Storage:
        style: column
      Tools:
        style: column
    showStats: false
    statusStyle: dot
    target: _self
    title: Home
  widgets.yaml: |
    - resources:
      cpu: true
      cputemp: true
      memory: true
      disk: [/,/app/config]
      uptime: true
    - openweathermap:
      label: Berlin
      latitude: 52.51
      longitude: 13.44
      units: metric
      provider: openweathermap
      cache: 30
      format:
        maximumFractionDigits: 1
    - datetime:
      text_size: md
      format:
        timeStyle: short
        hourCycle: h23
