---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_NEXTDNS_ID: "{{ .NEXTDNS_ID }}"
        HOMEPAGE_VAR_NEXTDNS_API: "{{ .NEXTDNS_API }}"
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .PORTAINER_TOKEN }}"
        ## Default
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HASS_TOKEN }}"
        HOMEPAGE_VAR_PAPERLESS_TOKEN: "{{ .HOMEPAGE_VAR_PAPERLESS_TOKEN }}"
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_USERNAME }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_PASSWORD }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_READARR_TOKEN: "{{ .READARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_WHISPARR_TOKEN: "{{ .WHISPARR_API_KEY }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        ## Media
        HOMEPAGE_VAR_JELLYSEERR_TOKEN: "{{ .JELLYSEERR_API_KEY }}"
        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .JELLYFIN_TOKEN }}"
        HOMEPAGE_VAR_TAUTULLI_TOKEN: "{{ .TAUTULLI_API_KEY }}"
        ## Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASS }}"
        HOMEPAGE_VAR_HEALTHCHECK_TOKEN: "{{ .HOMEPAGE_VAR_HEALTHCHECK_TOKEN }}"
        HOMEPAGE_VAR_HEALTHCHECK_UUID: "{{ .HOMEPAGE_VAR_HEALTHCHECK_UUID }}"
  dataFrom:
  - extract:
      key: cloudflare
  - extract:
      key: grafana
  - extract:
      key: healthcheck
  - extract:
      key: home-assistant
  - extract:
      key: nextdns
  - extract:
      key: jellyseerr
  - extract:
      key: paperless
  - extract:
      key: jellyfin
  - extract:
      key: portainer
  - extract:
      key: prowlarr
  - extract:
      key: qbittorrent
  - extract:
      key: radarr
  - extract:
      key: readarr
  - extract:
      key: lidarr
  - extract:
      key: sonarr
  - extract:
      key: whisparr
