---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      homepage:
   #     replicas: 2
        strategy: RollingUpdate
        annotations:
          configmap.reloader.stakater.com/reload: *app
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.9.12@sha256:31820dab8e3f830f8a88c3ef1b3a1d103b899f2b8f2f51879d960d0db164a573
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              TZ: ${TIMEZONE}
          #  envFrom:
          #    - secretRef:
          #        name: homepage-secret
            resources:
              requests:
                cpu: 15m
                memory: 200Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/name: "HomeLab"
          gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
       #   gethomepage.dev/group: "A New Group"
       #   gethomepage.dev/icon: "homepage.png"
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        type: configMap
        name: *app
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      create: true
