apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app victoria-logs
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.6.6
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: victoria-logs
    server:
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 200Mi
          ephemeral-storage: 2Gi
      ingress:
        enabled: true
        ingressClassName: intern
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Observability
          gethomepage.dev/name: VictoriaLogs
          gethomepage.dev/icon: si-victoriametrics
          gethomepage.dev/id: "{{ .Release.Name }}"
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        hosts:
          - name: &host "logs.${SECRET_DOMAIN}"
            path: /
            port: http
        tls: [hosts: [*host]]
    fluent-bit:
      enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 100Mi
          ephemeral-storage: 2Gi
