---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr-exporter
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/exporters/radarr-exporter/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 6h
  timeout: 3m
