---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: office
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 60m
  path: "./kubernetes/apps/office/immich/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: dragonfly-cluster
    - name: external-secrets-stores
