---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: spegel-helm-values
  values:
    grafanaDashboard:
      enabled: true
    serviceMonitor:
      enabled: true
