---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app goldilocks
spec:
  interval: 15m
  chart:
    spec:
      interval: 15m
      chart: goldilocks
      version: 8.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          memory: 105M
        limits:
          memory: 105M
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.12.0@sha256:7ac22e90baa6537caca01bdcbb960d1b8a2799c616cb222b2afa702a1f5d59bc
      pullPolicy: Always
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Goldilocks"
          gethomepage.dev/group: "Observability"
          gethomepage.dev/icon: "https://raw.githubusercontent.com/FairwindsOps/goldilocks/master/pkg/dashboard/assets/images/favicon.ico"
          gethomepage.dev/description: "Kubernetes Resource Recommendations"
        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: goldilocks-tls
      resources:
        requests:
          memory: 105M
        limits:
          memory: 105M
