---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 15m
  chart:
    spec:
      chart: podinfo
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    resources:
      requests:
        cpu: 1m
        memory: 16Mi
      limits:
        cpu: 500m
        memory: 100Mi

    ingress:
      enabled: "true"
      ClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hajimari.io/appName: "podinfo"
        hajimari.io/enable: "true"
        hajimari.io/icon: "alarm-light-outline"

      hosts:
        - host: &host "podinfo.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific

      tls:
        - hosts:
            - *host
