---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./alertmanager/ks.yaml
  - ./gatus/ks.yaml
  - ./goldilocks/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./kepler/ks.yaml
  - ./kromgo/ks.yaml
  - ./loki/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./vector/ks.yaml
  - ./victoria-metrics/ks.yaml
  # Exporters
  - ./exporters
