---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./alertmanager.ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./victoria-metrics/ks.yaml
  - ./kromgo/ks.yaml
  - ./goldilocks/ks.yaml
  # Exporters
  - ./exporters

