---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: radarr-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APIKEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
