---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: flux-system
spec:
  path: ./kubernetes/apps/home/portainer/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: portainer
      namespace: portainer
  interval: 360m
  retryInterval: 1m
  timeout: 3m
