---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name fritzbox-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      fritzbox-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sberk42/fritzbox_exporter
              tag: latest@sha256:9943df16e5237146ed616fc9bcff1918ba4e72a8ad17e0015e7d803799ebbef9
            env:
              GATEWAY_URL: http://192.168.2.1:49000
              LISTEN_ADDRESS: 0.0.0.0:9133
            envFrom:
              - secretRef:
                  name: fritzbox-exporter-secret
            resources:
              requests:
                cpu: 10m
                memory: 31Mi
              limits:
                memory: 31Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *name
        ports:
          http:
            port: 9133

    serviceMonitor:
      app:
        serviceName: *name
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: node
