---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name fritzbox-exporter
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      fritzbox-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/sberk42/fritzbox_exporter
              tag: latest@sha256:e153c2ff0c8c4a2fb9ccee9d72832d85281cc0a09ff4b364d45bba67eb0a0acc
            env:
              GATEWAY_URL: http://192.168.2.1:49000
              LISTEN_ADDRESS: 0.0.0.0:9133
            envFrom:
              - secretRef:
                  name: fritzbox-exporter-secret
            resources:
              requests:
                cpu: 10m
                memory: 31Mi
              limits:
                memory: 31Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *name
        ports:
          http:
            port: 9133

    serviceMonitor:
      app:
        serviceName: *name
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
            relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                targetLabel: node
