---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fritzbox-exporter
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: fritzbox-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        FRITZ_USERNAME: "{{ .FRITZBOX_USERNAME }}"
        FRITZ_PASSWORD: "{{ .FRITZBOX_PASSWORD }}"
  dataFrom:
    - extract:
        key: fritzbox-monitor
