---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: archivist-metrics
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: archivist-metrics-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ES_USER: "{{ .TA_ELASTIC_USER }}"
        ES_PASSWORD: "{{ .TA_ELASTIC_PASSWORD }}"
  dataFrom:
    - extract:
        key: archivist-es
