---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app homebridge-test
  labels:
    kubernetes.io/service-name: *app
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Diverses für iPhone
    gethomepage.dev/group: Apple HomeKit
    gethomepage.dev/icon: homebridge.svg
    gethomepage.dev/name: Homebridge Test
    gethomepage.dev/widget.type: homebridge
    gethomepage.dev/widget.url: http://homebridge-test.home/
    gethomepage.dev/widget.fields: '["updates", "child_bridges"]'
    gethomepage.dev/widget.username: fake
    gethomepage.dev/widget.password: fake
    gethomepage.dev/weight: "2"
spec:
  ingressClassName: internal
  rules:
  - host: "hb-test.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: *app
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8079
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: &app homebridge-test # Must be equal to Service name for automatic mapping
  namespace: home
  labels:
    kubernetes.io/service-name: *app
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: 8079
endpoints:
  - addresses:
      - 192.168.2.121
