---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 100T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_ADDR}
    path: "/Medien"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
  annotations:
    k8up.io/backup: false
spec:
  storageClassName: manual
  volumeName: media-library
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
