---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvme-share
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 4T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_ADDR}
    path: "/NVME"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvme-share
  namespace: media
  annotations:
    k8up.io/backup: false
spec:
  storageClassName: manual
  volumeName: nvme-share
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
