---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bluray
  namespace: media
spec:
  storageClassName: manual
  capacity:
    storage: 50T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.2.115
    path: "/Bluray"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bluray
  namespace: media
  annotations:
    k8up.io/backup: false
spec:
  storageClassName: manual
  volumeName: bluray
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
