---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: influxdb-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: influxdb
        property: admin_password
    - secretKey: admin-token
      remoteRef:
        key: influxdb
        property: admin_token
