---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app influxdb
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  # Values link: https://github.com/influxdata/helm-charts/blob/master/charts/influxdb2/values.yaml
  values:
    image:
      repository: docker.io/library/influxdb
      tag: 2.7.8-alpine

    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"

    pdb:
      create: false

    adminUser:
      organization: "home"
      user: "admin"
      bucket: "default"
      existingSecret: "influxdb-secrets"

    persistence:
      enabled: true
      useExisting: true
      name: local-volume-database
      subPath: *app

    ingress:
      enabled: true
      className: internal
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Time Series DB
        gethomepage.dev/group: data-platform
        gethomepage.dev/icon: influxdb.png
        gethomepage.dev/name: InfluxDB
      hostname: "influxdb.${SECRET_DOMAIN}"
      tls: true

    service:
      type: LoadBalancer
      loadBalancerIP: 10.172.90.40
