---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: ghcr.io/volschin/calibre-web
              tag: 0.6.23@sha256:bfb483d123ef338eb762c3bb070dd9c6d2f46e44ca0a31049ac07c342f35e6ac
            env:
              TZ: ${TIMEZONE}
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 15m
                memory: 249M
              limits:
                memory: 299M
    service:
      main:
        controller: main
        ports:
          http:
            port: 8083
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Calibre-Web
          gethomepage.dev/icon: calibre-web.png
          gethomepage.dev/id: "{{ .Release.Name }}"
          gethomepage.dev/description: e-Book Verwaltung
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.${SECRET_DOMAIN}/css/base/calibreweb/nord.css"></head>';
            sub_filter_once on;
        hosts:
          - host: books.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      media:
        existingClaim: media-datastore
        advancedMounts:
          main:
            main:
              - path: /media
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
