---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vault
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openbao.github.io/openbao-helm
      chart: openbao
     # version: 0.40.0
      sourceRef:
        kind: HelmRepository
        name: openbao
        namespace: flux-system
      interval: 5m
  values:
    injector:
      agentImage:
        registry: quay.io
        repository: openbao/openbao
        tag: 2.0.0-beta20240618
    server:
      image:
        registry: quay.io
        repository: openbao/openbao
        tag: 2.0.0-beta20240618
      dataStorage:
        enabled: true
        storageClass: "longhorn"
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: false
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              telemetry {
                unauthenticated_metrics_access = "true"
              }
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
    ingress:
      enabled: true
      annotations: |
        kubernetes.io/ingress.class: internal

      hosts:
        - host: &host "vault.${SECRET_DOMAIN}"
          paths: ["/"]
      tls:
        - hosts:
            - *host
          secretName: vault-tls
    ui:
      enabled: true
      serviceType: "ClusterIP"
