---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secret-manager
  target:
    name: lidarr-secret
    template:
      engineVersion: v2
      data:
        # App
        LIDARR__API_KEY: "{{ .LIDARR__API_KEY }}"
        LIDARR__POSTGRES_HOST: &dbHost ${POSTGRES_URL}
        LIDARR__POSTGRES_PORT: "5432"
        LIDARR__POSTGRES_USER: &dbUser "{{ .LIDARR_POSTGRES_USER }}"
        LIDARR__POSTGRES_PASSWORD: &dbPass "{{ .LIDARR_POSTGRES_PASS }}"
        LIDARR__POSTGRES_MAIN_DB: &db lidarr_main
        # Postgres Init
        INIT_POSTGRES_DBNAME: *db
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: cloudnative-pg
