---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cups
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      # https://hub.docker.com/r/olbat/cupsd
      repository: docker.io/olbat/cupsd
      tag: stable-2024-08-09@sha256:da6bcbac3990df8376bfacebddaca22d6ba49962d829dbb787a3e25c26aaa5e8
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: "192.168.2.110"
        ports:
          http:
            port: 631
          udp:
            enabled: true
            port: 631
            protocol: UDP
    # https://www.cups.org/doc/man-cupsd.conf.html (See 'ServerName')
    persistence:
      config:
        enabled: true
        type: configMap
        name: cupsd-conf
        subPath: cupsd.conf
        mountPath: /etc/cups/cupsd.conf
        readOnly: true
      dbus:
        enabled: true
        type: hostPath
        mountPath: /var/run/dbus
        hostPath: /var/run/dbus
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: print
        hosts:
          - host: &host "print.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
