---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: archivist-metrics
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/exporters/archivist-metrics/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 120m
  retryInterval: 1m
  timeout: 3m
