---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  # dependsOn:
  #   - name: bitwarden
  #     namespace: external-secrets
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
      interval: 1m
    webhook:
      serviceMonitor:
        enabled: true
        interval: 1m
    certController:
      serviceMonitor:
        enabled: true
        interval: 1m
