---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "devcontainer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  pull_request:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  schedule:
    - cron: "0 0 * * *"
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  devcontainer:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@aa33708b10e362ff993539393ff100fa93ed6a27 # v3.5.0
        with:
          platforms: linux/amd64 #,linux/arm64

      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: devcontainers/ci@a56d055efecd725e8cfe370543b6071b79989cc8 # v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          # cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          imageTag: base,latest
          platform: linux/amd64 #,linux/arm64
          configFile: .devcontainer/ci/devcontainer.json
          push: ${{ github.event_name == 'pull_request' && 'never' || 'always' }}
