# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "kubernetes/**.md"
      - "README.md"
permissions: {}

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # checkout
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      # setup taskfile
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # setup cache for social cards
      - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          key: ${{ github.ref }}
          path: .cache

      # create pages for docs
      - name: Create pages for docs
        run: task docs

      # deploy docs
      - uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/requirements.txt
