name: Kubescape scanning for misconfigurations
on:
  push:
    branches: [ main ]
    paths: ["kubernetes/**.yaml"]
permissions: {}
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
        frameworks: NSA,MITRE,AllControls
        # Optional: Scan a specific path. Default will scan the whole repository
        files: "kubernetes/**.yaml"
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@530d4feaa9c62aaab2d250371e2061eb7a172363 # v3
      with:
        sarif_file: results.sarif
