name: Kubescape scanning for misconfigurations
on:
  push:
    branches: [ "main", "renovate/**" ]
    paths: ["kubernetes/**.yaml"]
permissions: {}
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - uses: kubescape/github-action@c91feb3b8dd145ff8a094f91d6836bba4abc4293 # v3.0.5
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
        frameworks: NSA,MITRE,AllControls
        # Optional: Scan a specific path. Default will scan the whole repository
        files: "kubernetes/**.yaml"
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@662472033e021d55d94146f66f6058822b0b39fd # v3.27.0
      with:
        sarif_file: results.sarif
