name: Kubescape scanning for misconfigurations
on:
  push:
    branches: [ "main", "renovate/**" ]
    paths: ["kubernetes/**.yaml"]
permissions: {}
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: kubescape/github-action@c91feb3b8dd145ff8a094f91d6836bba4abc4293 # v3.0.5
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
        frameworks: NSA,MITRE,AllControls
        # Optional: Scan a specific path. Default will scan the whole repository
        files: "kubernetes/**.yaml"
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@2c779ab0d087cd7fe7b826087247c2c81f27bfa6 # v3.26.5
      with:
        sarif_file: results.sarif
