name: Suggest autofixes with Kubescape for PR by reviews
on:
  pull_request_target:
permissions: {}
jobs:
  kubescape-fix-pr-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
      with:
        egress-policy: audit
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - uses: reviewdog/action-setup@3f401fe1d58fe77e10d665ab713057375e39b887 # v1.3.0
    - run: reviewdog -version
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
    - uses: kubescape/github-action@c9749b84d138c0cbbb702b258774954f5463b82e # v3.0.21
      with:
        files: ${{ steps.changed-files.outputs.all_changed_files }}
        frameworks: NSA,MITRE,AllControls
        fixFiles: true
        continue-on-error: true
        format: "sarif"
    - name: PR Suggester according to SARIF file
      if: github.event_name == 'pull_request_target'
      uses: HollowMan6/sarif4reviewdog@1dce5522fa5792a629d99ef000e474699a9a9b8e # v1.0.1
      with:
        file: 'results.sarif'
        level: warning
